### ISSUE TITLE
请问客户端中同时使用了LitJson和SimpleJson库，有啥特殊原因么？

### ISSUE THREAD

**Issue by tianxiawuzhe** [doctording/pomelo_unity_ChessOfRunFast#1]
你好，我看到客户端脚本中，同时使用了LitJson和SimpleJson库，是否只使用Simple或Lit就可完成Json的操作？这两个库的区别主要是什么？感谢回复哦~~~

**Comment by doctording** [comment]
应该可以只使用一个json库的，当初是由于我都不会用，所以两个都学了下，所以代码中可以看到有两个库

**Comment by tianxiawuzhe** [comment]
多谢多谢~~
